apiVersion: v1
kind: Secret
metadata:
  name: secrets-application
type: Opaque
data:
  # Les valeurs doivent être encodées en base64.
  # Commande pour encoder :
  # echo -n "ma-cle-secrete" | base64

  API_KEY: bWEtY2xlLXNlY3JldGU=
  DATABASE_PASSWORD: cGFzc3dvcmQxMjM=
