[project]
name = "seleniumex"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pdfkit>=1.0.0",
    "pypdf2>=3.0.1",
    "requests>=2.32.5",
    "selenium>=4.40.0",
]
